from config.llm_config import get_llm
from langchain_components.prompts.retrieval_classifier_prompt import retrieval_classifier_prompt
from langchain_components.parsers.retrieval_classifier_parser import retrieval_classifier_parser

retrieval_classifier_chain = retrieval_classifier_prompt | get_llm(temperature=0) | retrieval_classifier_parser